include(string(@__DIR__, "/PARAMETERS_arlett.jl"))
include(string(@__DIR__, "/locations_arlett.jl"))
include(string(@__DIR__, "/spawn_arlett.jl"))
include(string(@__DIR__, "/flow_arlett.jl"))
include(string(@__DIR__, "/arlett_sim.jl"))
include(string(@__DIR__, "/arlett_animation.jl"))
include(string(@__DIR__, "/arlett_noflow.jl"))
