include("PARAMETERS_arlett.jl")
include("locations_arlett.jl")
include("spawn_arlett.jl")
include("flow_arlett.jl")
include("arlett_sim.jl")
include("arlett_animation.jl")
include("arlett_sim.jl")
